import Header from '@/components/Header';

export const metadata = {
  title: 'App Router',
}

export default function Page() {
  return (
    <>
      <Header />
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 border-y">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Welcome to AI Text and Title Creation
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Harness the power of AI to generate creative and engaging text for your advertising and marketing campaigns.
                </p>
                <div className="space-x-4">
                  <button className="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2">Get Started</button>
                </div>
              </div>
              <div>
                {/* <img src="/placeholder.svg" alt="AI Text Creation" className="mx-auto aspect-[4/3] overflow-hidden rounded-t-xl object-cover" width="400" height="300" /> */}
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Our AI-powered Text Creation Process
                </h2><p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Using advanced machine learning algorithms, our system generates compelling text that captures attention and drives engagement.
                </p></div><div className="w-full aspect-[4/3]">
                <div style={{ width: '100%', height: '100%' }}>
                  <div style={{ position: 'relative' }}>
                  </div></div></div></div></div></section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800"><div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6"><div className="space-y-3"><h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
          Testimonials
        </h2><p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            See what our satisfied customers have to say about our AI-powered text creation service.
          </p></div><div className="flex flex-wrap justify-center items-center gap-4"><div className="rounded-lg border bg-card text-card-foreground shadow-sm" data-v0-t="card"><div className="flex flex-col space-y-1.5 p-6"><span className="relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full"></span><div className="ml-4"><h3 className="text-lg font-bold">John Doe</h3><div className="inline-flex items-center rounded-full border px-2.5 py-0.5 w-fit text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-primary text-primary-foreground hover:bg-primary/80">CEO, TechCo</div></div></div><div className="p-6"><p className="text-gray-500">
            The text generated by this service was spot on. It greatly improved the engagement of our marketing campaigns.
          </p></div></div><div className="rounded-lg border bg-card text-card-foreground shadow-sm" data-v0-t="card"><div className="flex flex-col space-y-1.5 p-6"><span className="relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full"></span><div className="ml-4"><h3 className="text-lg font-bold">Jane Smith</h3><div className="inline-flex items-center rounded-full border px-2.5 py-0.5 w-fit text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-primary text-primary-foreground hover:bg-primary/80">Marketing Manager, BizCorp</div></div></div><div className="p-6"><p className="text-gray-500">
            I was skeptical at first, but the results speak for themselves. This service is a game changer.
          </p>
          </div>
            </div>
          </div>
        </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          ©  AI Text and Title Creation. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <a className="text-xs hover:underline underline-offset-4" href="#">
            Contact
          </a>
          <a className="text-xs hover:underline underline-offset-4" href="#">
            Twitter
          </a>
          <a className="text-xs hover:underline underline-offset-4" href="#">
            Facebook
          </a>
          <a className="text-xs hover:underline underline-offset-4" href="#">
            LinkedIn
          </a>
        </nav>
      </footer>
    </>
  )
}
